version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: sudo npm -g install codecov
      - run: make install
      - run: make test
      - run: codecov
    environment:
      NPM_CONFIG_PROGRESS: false
      NPM_CONFIG_SPIN: false
      TEST_REPORTS_DIR: $CIRCLE_TEST_REPORTS
  publish:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run: make build
      - run: npm config set "//registry.npmjs.org/:_authToken" $NPM_AUTH
      - run: npm publish .

workflows:
  version: 2
  test_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
            branches:
              ignore: /.*/
